### ISSUE TITLE
Unhandled Exception: System.IO.IOException: The handle is invalid.

### ISSUE THREAD

**Issue by Pamnig** [2365103939/ExtremeDumper#11]
[LDHK] DllMain: Loaded
[LDHK] DllMain: Monitor created
[LDHK] LoaderHookMonitorLoop: Found nLoadImage at 74D26310 by ECall
[LDHK] InstallHook: 1
[LDHK] LoaderHookMonitorLoop: LDHK_MONITOR_CLR at 74D26310

Unhandled Exception: System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.Console.Clear()
   at Colorful.Console.Clear()
   at Main.Menu()
   at Program.Main(String[] args)

**Comment by wwh1004** [comment]
AllocConsole was called twice then previous stdhandle is invalid

**Comment by saltasatelites** [comment]
No updates for two years.
